on:
  push:
    branches:
    - main
    paths:
      - 'spa/**'
      - 'Dockerfile'
env:
  CONTAINER_IMAGE: identicum/${{github.event.repository.name}}:latest
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
  build-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Hub login
      run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
    - name: Build image 
      run: docker build -t $CONTAINER_IMAGE .
      working-directory: .
    - name: Push to Docker Hub
      run: docker push $CONTAINER_IMAGE
